version: '3'
services:
  dhcp-serveis:
    image: docker.cloudsmith.io/isc/docker/kea-dhcp4:2.6.0
    container_name: dhcp-docker-serveis
    network_mode: "host"  # Això farà que no doni errors de permisos
    ports:
      - "67:67/udp"
    volumes:
      - ./kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf
    restart: always
